spring:
  application:
    name: elector-demo-simple
  cloud:
    config:
      enabled: false
    discovery:
      client:
        simple:
          instances:
            elector-demo-simple:
              - instanceId: 8832fea7-60b0-400a-95b6-828968a907d9
                host: ${PEER_A_HOSTNAME:10.0.0.1}
              - instanceId: 4707bc12-d32f-4aef-93ce-4f9663711ae8
                host: ${PEER_B_HOSTNAME:10.0.0.2}
              - instanceId: c3b1ef50-7007-470a-b544-553112aa645d
                host: ${PEER_C_HOSTNAME:10.0.0.3}
              - instanceId: fcc18ce2-5726-4ab9-adf5-161ca58a284d
                host: ${PEER_D_HOSTNAME:10.0.0.4}
    elector:
      enabled: true
      service-name: ${spring.application.name}
      listener-port: 12321
      heartbeat-interval-millis: 1000
      heartbeat-timeout-millis: 3000
      ballot-timeout-millis: 1000
      pool-size: 1
      ballot-type: QUORUM
      instance-id: 8832fea7-60b0-400a-95b6-828968a907d9
  jackson:
    serialization.INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ERROR
    com.elector: DEBUG
