server:
  port : 8085

spring:
  application:
    name: elector-demo
  cloud:
#    inetutils:
#      useOnlySiteLocalInterfaces: true
#      preferred-networks: 192\.168\.88\..*
    config:
      enabled: false
    discovery:
      client:
        simple:
          local:
            instanceId: ${spring.application.name}#0
            serviceId: ${spring.application.name}
            host: 192.168.88.230
          instances:
            elector-demo:
              - instanceId: ${spring.application.name}#1
                host: 192.168.123.1
              - instanceId: ${spring.application.name}#1
                host: 192.168.123.2
              - instanceId: ${spring.application.name}#1
                host: 192.168.123.3
    elector:
      enabled: true
      service-name: ${spring.application.name}
#      hostname: 192.168.88.230
      listener-port: 12321
      heartbeat-interval-millis: 1000
      heartbeat-timeout-millis: 2000
      poolSize: 1
    kubernetes:
      enabled: false
      discovery:
        enabled: false
  jackson:
    serialization.INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ERROR
    com.elector: DEBUG
