elector:
  enabled: true
  service-name: ${spring.application.name}
  listener-port: 12321
  heartbeat-interval-millis: 1000
  heartbeat-timeout-millis: 2000
  poolSize: 1

server:
  port : 8085

spring:
  application:
    name: elector-demo
  cloud:
    config:
      enabled: false
    kubernetes:
      enabled: false
      discovery:
        enabled: false
  jackson:
    serialization.INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ERROR
    com.elector: DEBUG
