spring:
  application:
    name: elector-demo-kubernetes
  cloud:
    config:
      enabled: false
    kubernetes:
      enabled: true
      discovery:
        enabled: true
  jackson:
    serialization.INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ERROR
    com.elector: DEBUG
