spring:
  application:
    name: elector-demo
  cloud:
    config:
      enabled: false
    kubernetes:
      enabled: true
      discovery:
        enabled: true
    elector:
      enabled: true
      pool-size: 4
  jackson:
    serialization.INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
    info:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ERROR
    com.elector: DEBUG
#    org.springframework.cloud.kubernetes: DEBUG
#    io.fabric8.kubernetes.client: DEBUG
