server:
  port : 8085

spring:
  application:
    name: elector-demo-kubernetes
  cloud:
    config:
      enabled: false
    elector:
      enabled: true
      service-name: ${spring.application.name}
#      hostname: 192.168.88.230
      listener-port: 12321
      heartbeat-interval-millis: 1000
      heartbeat-timeout-millis: 3000
      ballot-timeout-millis: 1000
      poolSize: 1
      ballot-type: QUORUM
    kubernetes:
      enabled: true
      discovery:
        enabled: true
  jackson:
    serialization.INDENT_OUTPUT: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: ERROR
    com.elector: DEBUG
