kind: Service
apiVersion: v1
metadata:
  name: elector-demo
spec:
  selector:
    app: elector-demo
  ports:
    - protocol: TCP
      port: 8080
  type: LoadBalancer
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: elector-demo
spec:
  selector:
    matchLabels:
      app: elector-demo
  replicas: 4
  template:
    metadata:
      labels:
        app: elector-demo
    spec:
      containers:
        - name: elector-demo
          image: elector-demo:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
